version: '3.9'
services:
  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: inventory
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - '6379:6379'
  api:
    build: ./apps/api
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/inventory
      REDIS_URL: redis://redis:6379
      HMAC_SECRET: local-secret
    depends_on:
      - postgres
      - redis
    ports:
      - '3000:3000'
  web:
    build: ./apps/web
    depends_on:
      - api
    ports:
      - '5173:4173'
