name: Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'staging'
      rotation:
        description: 'Secret rotation'
        required: false
        default: 'false'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: azure/setup-kubectl@v3
      - uses: azure/setup-helm@v4
      - name: Helm upgrade
        run: |
          helm upgrade --install service-inventory infra/helm/inventory \
            --namespace service-inventory --create-namespace \
            --set image.tag=${GITHUB_SHA::7} --set web.tag=${GITHUB_SHA::7}
